#SPDX-License-Identifier: MIT-0
---
# tasks file for server_hardening
- name: Devsec_os_hardening
  vars:
    os_auditd_enabled: false
    os_immutable_fs: true
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      net.ipv4.ip_forward: 1
  ansible.builtin.include_role:
    name: devsec.hardening.os_hardening
  tags: [devsec, devsec_os_hardening]

- name: Devsec_ssh_hardening
  vars:
    ssh_immutable_fs: true
    ssh_authorized_keys_file: '.ssh/authorized_keys.d/ignition'
  ansible.builtin.include_role:
    name: devsec.hardening.ssh_hardening
  tags: [devsec, devsec_ssh_hardening]

- name: Drop icmp requests to tun0
  ansible.builtin.command:
    cmd: bash -c "firewall-cmd --zone external --permanent --add-icmp-block=$(firewall-cmd --get-icmptypes | sed 's/time-exceeded //g' | sed 's/fragmentation-needed //g' | sed 's/packet-too-big //g' | sed 's/ / --add-icmp-block=/g')"


  #ansible.posix.firewalld:

# - name: Install/configure clamav

# - name: Install/configure Snort/IDS

# - name: Install cockpit
